# Generated by Django 3.1 on 2020-09-19 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_version', models.CharField(max_length=200)),
                ('other_details', models.CharField(max_length=200)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role_code', models.IntegerField()),
                ('other_details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_address', models.CharField(max_length=200)),
                ('staff_contact', models.CharField(max_length=200)),
                ('staff_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fooddelivery.staffrole')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_address', models.CharField(max_length=150)),
                ('restaurant_contact', models.CharField(max_length=150)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fooddelivery.menu')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_description', models.CharField(max_length=150)),
                ('item_price', models.DecimalField(decimal_places=5, max_digits=50)),
                ('other_details', models.CharField(max_length=150)),
                ('menu', models.ManyToManyField(blank=True, to='fooddelivery.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=False, max_length=200)),
                ('address', models.CharField(default=False, max_length=200)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=5, max_digits=50)),
                ('order_date', models.CharField(max_length=6)),
                ('order_time', models.CharField(max_length=6)),
                ('customer', models.ManyToManyField(blank=True, to='fooddelivery.Customer')),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fooddelivery.menuitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddelivery.staff')),
            ],
        ),
    ]
