# Generated by Django 3.1 on 2020-09-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fooddelivery', '0002_auto_20200919_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('restaurant_address', models.CharField(max_length=150)),
                ('restaurant_contact', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fooddelivery.menu'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
