# Generated by Django 3.1 on 2020-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0005_menu_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
